### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by Berl-Spitz** [vvb2060/Magica#1]
My boot.img didn't become rooted after patching with Magisk (seemingly because it uses a rare SAR).

May I suggest an option that the app just dumps the boot.img to the accessible internal storage, so I can manually patch it.

Maybe making a commnad to run an external bash script would be best, as this allows custom dumping/writing partitions etc.

Many thanks,
B. Spitz

**Comment by yunasc** [comment]
I would add to this, that just giving some shell/terminal would be also nice.
Would help us with https://github.com/polygraphene/DirtyPipe-Android/issues/3

**Comment by vvb2060** [comment]
https://github.com/vvb2060/Magica/blob/55afffa713acd8efe2413e28acbfea771e2b6d69/app/src/main/java/io/github/vvb2060/puellamagi/MainActivity.java#L85-L91

This is an open source project, you can do whatever you want, like start sshd. Why are you seeking my technical support?
